services:
  call-analyzer-backend:
    build: 
      context: ./Nodejs
      dockerfile: Dockerfile
    image: call-analyzer-backend-img
    container_name: call-analyzer-backend-container
    ports:
      - "5002:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - weam_app-network
    volumes:
      - ./Nodejs/logs:/app/logs
      - ./Nodejs/uploads:/app/uploads

  call-analyzer-frontend:
    build:
      context: ./Nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENVIRONMENT: ${NEXT_PUBLIC_ENVIRONMENT}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_COOKIE_NAME: ${NEXT_PUBLIC_COOKIE_NAME}
        NEXT_PUBLIC_COOKIE_PASSWORD: ${NEXT_PUBLIC_COOKIE_PASSWORD}
    image: call-analyzer-frontend-img
    container_name: call-analyzer-frontend-container
    ports:
      - "5003:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - weam_app-network
    depends_on:
      - call-analyzer-backend

networks:
  weam_app-network:
    external: true
